---
title: Ananke
baseURL: 'https://gohugo-ananke-theme-demo.netlify.com/'
languageCode: en
theme: gohugo-theme-ananke
MetaDataFormat: yaml
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableGitInfo: true
enableRobotsTXT: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - JSON
  section:
    - HTML
    - JSON
algolia:
  index: testhugoagolia_8
  key:
  appID: Y5U3SE5SW2
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  description: The last theme you'll ever need. Maybe.
  faceboook: ''
  twitter: 'https://twitter.com/GoHugoIO'
  instagram: ''
  youtube: ''
  background_color_class: bg-black
  featured_image: /images/gohugo-default-sample-hero-image.jpg
