[build]
  publish = "public"
  command = "npm run build"


[context.production.environment]
  HUGO_VERSION = "0.34"
  HUGO_ENV = "dev"
  ALGOLIA_APPLICATION_ID = "Y5U3SE5SW2"
  ALGOLIA_INDEX_ID = "test3"


[context.deploy-preview.environment]
  HUGO_VERSION = "0.34"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.34"



# [context.production.environment]
#   HUGO_VERSION = "0.24.1"
#   HUGO_ENV = "development"

# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/
